#!/usr/bin/env python3
"""Render VectorPeak's bilingual GitHub profile README."""

from __future__ import annotations

import argparse
import json
import os
import re
import urllib.error
import urllib.request
from html import escape as html_escape
from pathlib import Path
from typing import Any


DEFAULT_BADGES = [
    ("Python", "3776AB", "python", "white"),
    ("Go", "00ADD8", "go", "white"),
    ("TypeScript", "3178C6", "typescript", "white"),
    ("React", "20232A", "react", "61DAFB"),
    ("Node.js", "339933", "node.js", "white"),
    ("FastAPI", "009688", "fastapi", "white"),
    ("RAG", "0F172A", "googlegemini", "white"),
    ("Hugging Face", "FFD21E", "huggingface", "111"),
    ("LangChain", "1C3C3C", "langchain", "white"),
    ("GitHub", "181717", "github", "white"),
]

PROJECT_AREAS = {
    "Coding agents",
    "CI / PR tooling",
    "MCP / protocol tooling",
    "Codebase maps",
    "Applied agents",
    "LLM tooling",
    "Research",
}

CONTRIBUTION_AREAS = [
    "AI infrastructure / model systems",
    "Agent frameworks / protocols / evals",
    "Applied AI / RAG / observability",
    "Recommender systems",
]

ZH_CONTRIBUTION_FIXES = {
    "Improve event connection handling and reconnection logic": "改进事件连接处理与重连逻辑，补充连接状态清理、监听器重建和异常分支处理，提升断线恢复的稳定性",
    "Prevent path traversal in asset materialization": "修复资源文件生成过程中的路径穿越漏洞，校验目录边界，阻止越权写入或覆盖文件，保障生成流程安全。",
    "Prevent path traversal vulnerability in knowledge base upload filenames": "修复知识库上传文件名的路径穿越漏洞，校验文件名边界，阻止目录逃逸。",
    "Prevent path traversal vulnerability in plugin upload filenames": "修复插件上传文件名的路径穿越漏洞，校验文件名边界，阻止目录逃逸。",
}

EN_CONTRIBUTION_FIXES = {
    "Improve event connection handling and reconnection logic": "Improved event connection handling and reconnection logic, strengthening disconnect recovery and long-running connection stability",
}

GENERATED_NOTICE = "<!-- AUTO-GENERATED by scripts/render_profile_readme.py. Edit profile-data.json for curated project notes. -->"
CJK_RE = re.compile(r"[\u3400-\u9fff\uf900-\ufaff]")
LLM_TRANSLATION_CACHE: dict[tuple[str, str], str] = {}


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def deep_merge(base: dict[str, Any], override: dict[str, Any]) -> dict[str, Any]:
    merged = dict(base)
    for key, value in override.items():
        if isinstance(value, dict) and isinstance(merged.get(key), dict):
            merged[key] = deep_merge(merged[key], value)
        else:
            merged[key] = value
    return merged


def number(value: Any) -> int:
    if value is None:
        return 0
    if isinstance(value, int):
        return value
    text = str(value).replace(",", "").replace("+", "").replace(" stars", "").strip()
    if text.lower().endswith("k"):
        return int(float(text[:-1]) * 1000)
    return int(text or 0)


def format_stars(value: Any) -> str:
    return f"{number(value):,}+"


def format_compact_stars(value: Any) -> str:
    count = number(value)
    if count >= 1000:
        return f"{count / 1000:.1f}k★"
    return f"{count}★"


def badge(label: str, color: str, logo: str, logo_color: str) -> str:
    safe_label = label.replace("-", "--").replace(" ", "%20")
    return f"![{label}](https://img.shields.io/badge/{safe_label}-{color}?logo={logo}&logoColor={logo_color})"


def md_escape(text: Any) -> str:
    return str(text).replace("|", "\\|").replace("\n", " ").strip()


def strip_terminal_period(text: Any) -> str:
    return md_escape(text).rstrip(".。")


def contains_cjk(text: Any) -> bool:
    return bool(CJK_RE.search(str(text)))


def env_value(*names: str) -> str:
    for name in names:
        value = os.environ.get(name)
        if value:
            return value.strip()
    return ""


def md_nowrap(text: Any) -> str:
    return md_escape(text).replace(" ", "&nbsp;")


def md_left(text: Any) -> str:
    return f'<div align="left">{md_escape(text)}</div>'


def md_left_raw(markdown: Any) -> str:
    return f'<div align="left">{markdown}</div>'


def md_center_raw(markdown: Any) -> str:
    return f'<div align="center">{markdown}</div>'


def html_text(text: Any) -> str:
    return html_escape(str(text).replace("\n", " ").strip(), quote=True)


def html_nowrap(text: Any) -> str:
    return html_text(text).replace(" ", "&nbsp;")


def html_link(label: Any, url: Any) -> str:
    return f'<a href="{html_text(url)}">{html_text(label)}</a>'


def project_link(project: dict[str, Any]) -> str:
    if project.get("url"):
        return f"[{project['name']}]({project['url']})"
    return str(project["name"])


def project_html_link(project: dict[str, Any]) -> str:
    if project.get("url"):
        return html_link(project["name"], project["url"])
    return html_text(project["name"])


def localized(project: dict[str, Any], key: str, lang: str) -> Any:
    if key == "area":
        return project.get("area", "")
    return project.get(f"{lang}_{key}") or project.get(key) or ""


def sorted_projects(projects: list[dict[str, Any]]) -> list[dict[str, Any]]:
    return sorted(
        projects,
        key=lambda item: (
            str(item.get("area", "")).lower(),
            -number(item.get("stars")),
            str(item.get("name", "")).lower(),
        ),
    )


def sorted_summary_projects(projects: list[dict[str, Any]]) -> list[dict[str, Any]]:
    return sorted(projects, key=lambda item: (-number(item.get("stars")), str(item.get("name", "")).lower()))


def infer_contribution_area(item: dict[str, Any]) -> str:
    repo = str(item.get("repo") or item.get("name") or "").rsplit("/", 1)[-1].lower()
    if repo in {
        "vllm",
        "transformers",
        "mooncake",
        "triton",
        "verl",
        "sglang",
        "flashinfer",
        "lmcache",
        "litellm",
    }:
        return "AI infrastructure / model systems"
    if repo in {
        "qwen-code",
        "openclaw",
        "mem0",
        "microsoft-agent-framework",
        "github-mcp-server",
        "mcp-go",
        "mcp-go-sdk",
        "agentscope",
        "agno",
        "ag-ui",
        "inspect_ai",
        "inspect-ai",
        "cline",
        "hivemind",
        "openhands",
    }:
        return "Agent frameworks / protocols / evals"
    if repo in {"astrbot", "dify", "ragflow", "langchain", "llamaindex", "google-genai", "python-genai"}:
        return "Applied AI / RAG / observability"
    if "recommender" in repo or "recbole" in repo:
        return "Recommender systems"
    return "Applied AI / RAG / observability"


def infer_area(repo: dict[str, Any]) -> str:
    text = f"{repo.get('name', '')} {repo.get('description', '')}".lower()
    if any(token in text for token in ("mcp", "protocol")):
        return "MCP / protocol tooling"
    if any(token in text for token in ("agent", "codex", "skill", "opensense", "profile", "readme")):
        return "Coding agents"
    if any(token in text for token in ("llm", "rag", "wiki", "langchain", "hugging")):
        return "LLM tooling"
    if any(token in text for token in ("kaggle", "research", "predictor", "classifier", "fault", "carbon")):
        return "Research"
    return "Applied agents"


def generated_notes(repo: dict[str, Any]) -> str:
    description = str(repo.get("description") or "").strip()
    if description:
        return description.rstrip(".。")
    return f"Public repository for {repo.get('name', 'this project')}"


def english_project_notes(repo: dict[str, Any]) -> str:
    notes = generated_notes(repo)
    if contains_cjk(notes):
        return f"Public repository for {repo.get('name', 'this project')}"
    return notes


def chinese_project_notes(repo: dict[str, Any]) -> str:
    notes = generated_notes(repo)
    if contains_cjk(notes):
        return notes
    return "待补充项目说明"


def auto_project(repo: dict[str, Any]) -> dict[str, Any]:
    en_notes = english_project_notes(repo)
    zh_notes = chinese_project_notes(repo)
    return {
        "area": infer_area(repo),
        "name": repo["name"],
        "url": repo.get("url"),
        "stars": repo.get("stars", 0),
        "notes": en_notes,
        "zh_notes": zh_notes,
        "en_notes": en_notes,
    }


def enrich_projects(data: dict[str, Any]) -> list[dict[str, Any]]:
    excluded = {str(name).lower() for name in data.get("excluded_projects", [])}
    owner = str(data.get("owner", "")).lower()
    if owner:
        excluded.add(owner)
    facts_by_name = {str(repo["name"]).lower(): repo for repo in data.get("public_repos", [])}
    projects = []
    for item in data.get("projects", []):
        if str(item.get("name", "")).lower() in excluded:
            continue
        project = dict(item)
        facts = facts_by_name.get(str(project.get("name", "")).lower())
        if facts:
            project["stars"] = facts.get("stars", project.get("stars", 0))
            project["url"] = facts.get("url") or project.get("url")
        projects.append(project)
    if data.get("auto_include_public_repos", True):
        configured = {str(project.get("name", "")).lower() for project in projects}
        for repo in data.get("public_repos", []):
            name = str(repo.get("name", "")).lower()
            if name and name not in configured and name not in excluded:
                projects.append(auto_project(repo))
                configured.add(name)
    return projects


def validate_projects(projects: list[dict[str, Any]]) -> None:
    for project in projects:
        missing = [key for key in ("area", "name") if key not in project]
        if missing:
            raise ValueError(f"Project {project!r} missing required fields: {', '.join(missing)}")
        if not (project.get("notes") or project.get("zh_notes") or project.get("en_notes")):
            raise ValueError(f"Project {project!r} must define notes, zh_notes, or en_notes")
        en_notes = project.get("en_notes")
        if en_notes and contains_cjk(en_notes):
            raise ValueError(f"Project {project.get('name')!r} has CJK text in en_notes: {en_notes!r}")
        if str(project["area"]) not in PROJECT_AREAS:
            raise ValueError(f"Unsupported project area {project['area']!r} for {project.get('name')!r}")


def validate_english_section(content: str) -> None:
    _, separator, english_section = content.partition("\n---\n\n")
    if not separator:
        raise ValueError("Rendered README is missing the bilingual section separator.")
    if contains_cjk(english_section):
        first_match = CJK_RE.search(english_section)
        start = max((first_match.start() if first_match else 0) - 40, 0)
        end = min((first_match.end() if first_match else 0) + 80, len(english_section))
        snippet = english_section[start:end].replace("\n", " ")
        raise ValueError(f"English README section contains CJK text near: {snippet!r}")


def project_summary(projects: list[dict[str, Any]], data: dict[str, Any], lang: str) -> str:
    ordered = sorted_summary_projects(projects)
    limit = int(data.get("project_summary_limit", 12))
    names = [str(project["name"]) for project in ordered[:limit]]
    count = number(data.get("public_project_count")) if data.get("public_project_count") is not None else len(projects)
    joined = ", ".join(names)
    if lang == "zh":
        return f"{count} 个公开项目，代表项目包括 {joined}。"
    return f"{count} public projects, led by {joined}."


def contribution_rows(data: dict[str, Any]) -> list[dict[str, Any]]:
    rows = []
    for item in data.get("upstream_prs", []):
        row = dict(item)
        if not (row.get("number") and row.get("url")):
            continue
        row["area"] = row.get("area") or infer_contribution_area(row)
        rows.append(row)
    return sorted(
        rows,
        key=lambda item: (
            -number(item.get("repo_stars")),
            str(item.get("repo") or item.get("name") or "").lower(),
            -number(item.get("number")),
        ),
    )


def contribution_summary(contributions: list[dict[str, Any]], data: dict[str, Any], lang: str) -> str:
    count = number(data.get("merged_pr_count")) if data.get("merged_pr_count") is not None else len(contributions)
    seen: set[str] = set()
    repos: list[str] = []
    for item in contributions:
        repo = contribution_repo_display(item, lang).strip()
        if repo and repo.lower() not in seen:
            seen.add(repo.lower())
            repos.append(repo)
    joined = ", ".join(repos[:5])
    if lang == "zh":
        return f"{count}+ merged upstream PRs，包括 {joined}。"
    return f"{count}+ merged upstream PRs, including {joined}."


def contribution_repo_display(item: dict[str, Any], lang: str) -> str:
    if lang == "en":
        display = str(item.get("repo_display_en") or item.get("repo_display") or item.get("repo") or "").strip()
        if contains_cjk(display):
            return "Upstream repository"
        return display
    return str(item.get("repo_display_zh") or item.get("repo_display") or item.get("repo") or "").strip()


def contribution_project_link(item: dict[str, Any], lang: str) -> str:
    label = f"{contribution_repo_display(item, lang)} ({format_compact_stars(item.get('repo_stars'))})"
    if item.get("repo_url"):
        return f"[{label}]({item['repo_url']})"
    return label


def contribution_pr_link(item: dict[str, Any]) -> str:
    number_value = item.get("number")
    if number_value:
        label = f"#{number_value}"
        if item.get("url"):
            return f"[{label}]({item['url']})"
        return label
    return md_escape(item.get("title") or "")


def normalize_contribution_title(title: Any) -> str:
    text = strip_terminal_period(title or "")
    text = re.sub(
        r"^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\([^)]+\))?!?:\s*",
        "",
        text,
        flags=re.IGNORECASE,
    ).strip()
    if not text:
        return ""
    return text[:1].upper() + text[1:]


def sanitize_zh_fix_text(text: Any, limit: int = 50) -> str:
    value = md_escape(text).strip().strip("\"'“”‘’")
    value = re.sub(r"\s+", " ", value)
    if not value:
        return ""
    if len(value) > limit:
        value = value[:limit].rstrip("，、；：,. ")
    if value[-1] not in "。！？":
        value += "。"
    return value


def llm_translate_contribution_title(title: str, repo: str) -> str:
    api_key = env_value("DASHSCOPE_API_KEY", "BAILIAN_API_KEY", "ALIYUN_BAILIAN_API_KEY")
    if not api_key:
        return ""
    cache_key = (repo, title)
    if cache_key in LLM_TRANSLATION_CACHE:
        return LLM_TRANSLATION_CACHE[cache_key]

    endpoint = env_value("PROFILE_TRANSLATION_BASE_URL") or "https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions"
    model = env_value("PROFILE_TRANSLATION_MODEL") or "qwen-plus"
    payload = {
        "model": model,
        "temperature": 0.1,
        "messages": [
            {
                "role": "system",
                "content": (
                    "你是技术简历和开源贡献文案编辑。把英文 PR 标题翻译并润色成中文，"
                    "用于 GitHub Profile 表格的 What I Fixed。只输出一句中文，50 字以内，"
                    "不要引号，不要解释，安全问题优先使用“漏洞”“路径穿越”等准确表述。"
                ),
            },
            {
                "role": "user",
                "content": f"仓库：{repo or 'upstream'}\nPR 标题：{title}",
            },
        ],
    }
    request = urllib.request.Request(
        endpoint,
        data=json.dumps(payload).encode("utf-8"),
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(request, timeout=20) as response:
            data = json.loads(response.read().decode("utf-8"))
    except (OSError, urllib.error.URLError, urllib.error.HTTPError, json.JSONDecodeError):
        return ""

    choices = data.get("choices") if isinstance(data, dict) else None
    if not choices:
        return ""
    message = choices[0].get("message", {}) if isinstance(choices[0], dict) else {}
    text = sanitize_zh_fix_text(message.get("content") or "")
    if not contains_cjk(text):
        return ""
    LLM_TRANSLATION_CACHE[cache_key] = text
    return text


def fallback_zh_contribution_fix(title: str) -> str:
    lower = title.lower()
    if "path traversal" in lower:
        if "knowledge base" in lower and "upload" in lower:
            return "修复知识库上传文件名的路径穿越漏洞，阻止目录逃逸。"
        if "plugin" in lower and "upload" in lower:
            return "修复插件上传文件名的路径穿越漏洞，阻止目录逃逸。"
        return "修复路径穿越漏洞，校验目录边界，阻止越权文件访问。"
    if lower.startswith(("fix ", "fixed ", "prevent ", "avoid ")):
        return "修复上游缺陷，完善边界校验与异常处理。"
    if lower.startswith(("feat ", "add ", "support ")):
        return "补充上游功能能力，完善相关实现。"
    if lower.startswith(("docs ", "document ", "update docs")):
        return "完善上游文档说明，提升使用指引清晰度。"
    return "完善上游实现，修复相关问题。"


def contribution_fix_text(item: dict[str, Any], lang: str) -> str:
    title = normalize_contribution_title(item.get("title") or "")
    if lang == "zh":
        text = item.get("zh_title") or ZH_CONTRIBUTION_FIXES.get(title)
        if text:
            return sanitize_zh_fix_text(text)
        repo = contribution_repo_display(item, lang)
        text = llm_translate_contribution_title(title, repo)
        if text:
            return text
        return fallback_zh_contribution_fix(title)
    text = item.get("en_title") or EN_CONTRIBUTION_FIXES.get(title, title)
    if contains_cjk(text):
        return "Merged upstream fix"
    return text


def render_contributions(lines: list[str], contributions: list[dict[str, Any]], lang: str) -> None:
    if not contributions:
        return
    lines.extend([
        "",
        "### 开源贡献" if lang == "zh" else "### Open Source Contributions",
    ])
    grouped: dict[str, list[dict[str, Any]]] = {}
    for item in contributions:
        area = str(item.get("area") or infer_contribution_area(item))
        grouped.setdefault(area, []).append(item)

    ordered_areas = [area for area in CONTRIBUTION_AREAS if area in grouped]
    ordered_areas.extend(sorted(area for area in grouped if area not in CONTRIBUTION_AREAS))
    for area in ordered_areas:
        lines.extend([
            "",
            f"#### {area}",
            "",
            "| Project | PR | What I Fixed |",
            "| :---: | :---: | :---: |",
        ])
        rows = sorted(
            grouped[area],
            key=lambda item: (
                -number(item.get("repo_stars")),
                str(item.get("repo") or item.get("name") or "").lower(),
                -number(item.get("number")),
            )
        )
        for item in rows:
            lines.append(
                "| "
                + " | ".join(
                    [
                        md_center_raw(contribution_project_link(item, lang)),
                        contribution_pr_link(item),
                        md_left(contribution_fix_text(item, lang)),
                    ]
                )
                + " |"
            )


def render_projects(lines: list[str], projects: list[dict[str, Any]], lang: str) -> None:
    lines.extend([
        "### 项目" if lang == "zh" else "### Projects",
        "",
        '<table width="100%">',
        "  <thead>",
        "    <tr>",
        '      <th align="center" width="16%">Area</th>',
        '      <th align="center" width="24%">Project</th>',
        '      <th align="left" width="8%">Stars</th>',
        '      <th align="center" width="52%">Notes</th>',
        "    </tr>",
        "  </thead>",
        "  <tbody>",
    ])
    for project in sorted_projects(projects):
        lines.extend([
            "    <tr>",
            f'      <td align="center">{html_nowrap(localized(project, "area", lang))}</td>',
            f"      <td>{project_html_link(project)}</td>",
            f"      <td>{html_text(format_stars(project.get('stars')))}</td>",
            f"      <td>{html_text(strip_terminal_period(localized(project, 'notes', lang)))}</td>",
            "    </tr>",
        ])
    lines.extend(["  </tbody>", "</table>"])


def render_section(lines: list[str], data: dict[str, Any], projects: list[dict[str, Any]], contributions: list[dict[str, Any]], lang: str, include_badges: bool) -> None:
    heading = data.get(f"{lang}_heading") or "## Hey, I'm VectorPeak 👋"
    lines.extend([str(heading), ""])

    if include_badges:
        badges = data.get("badges") or DEFAULT_BADGES
        parts = []
        if data.get("linkedin"):
            parts.append(f"[![LinkedIn](https://img.shields.io/badge/LinkedIn-0A66C2?logo=linkedin&logoColor=white)]({data['linkedin']})")
        parts.extend(badge(*item) for item in badges)
        lines.extend([" ".join(parts), ""])

    lines.extend([str(data.get("identity", "AI Programmer")), ""])
    if projects:
        lines.extend([f"- {project_summary(projects, data, lang)}"])
    if contributions:
        lines.extend([f"- {contribution_summary(contributions, data, lang)}"])
    if projects or contributions:
        lines.append("")
    if projects:
        render_projects(lines, projects, lang)
    render_contributions(lines, contributions, lang)


def render(data: dict[str, Any]) -> str:
    projects = enrich_projects(data)
    contributions = contribution_rows(data)
    validate_projects(projects)
    lines: list[str] = [GENERATED_NOTICE, ""]
    render_section(lines, data, projects, contributions, "zh", include_badges=True)
    lines.extend(["", "---", ""])
    render_section(lines, data, projects, contributions, "en", include_badges=False)
    content = "\n".join(lines).rstrip() + "\n"
    validate_english_section(content)
    return content


def write_output(path: Path, content: str) -> None:
    if path.name.lower() != "readme.md":
        raise ValueError(f"Refusing to overwrite non-README output path: {path}")
    tmp = path.with_name(path.name + ".tmp")
    tmp.write_text(content, encoding="utf-8", newline="\n")
    tmp.replace(path)


def main() -> int:
    parser = argparse.ArgumentParser(description="Render VectorPeak's bilingual GitHub profile README.")
    parser.add_argument("--data", required=True, type=Path)
    parser.add_argument("--facts", type=Path)
    parser.add_argument("--out", required=True, type=Path)
    args = parser.parse_args()

    data = load_json(args.data)
    if args.facts and args.facts.exists():
        data = deep_merge(data, load_json(args.facts))
    write_output(args.out, render(data))
    print(f"wrote: {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
